version: '2.2'
services:
  web:
    build: .
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - elasticsearch
    environment:
      DATABASE_URL: postgres://todoapp@postgres/todos
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - tcc-data-elastic:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  
volumes:
  tcc-data-elastic:
    driver: local
    
networks:
  esnet: